# Generated by Django 5.0.2 on 2024-02-28 15:34

import custom_admin.apps
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(default='', max_length=2000)),
                ('photo', models.ImageField(upload_to=custom_admin.apps.review_directory_path)),
            ],
        ),
    ]
