# Generated by Django 5.0.2 on 2024-02-28 15:41

import custom_admin.apps
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=custom_admin.apps.review_directory_path),
        ),
    ]
