# Generated by Django 5.0.2 on 2024-03-02 20:32

import custom_admin.apps
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_project_color_bigphotoproject_smallphotoproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background_1',
            field=models.ImageField(blank=True, null=True, upload_to=custom_admin.apps.back1_project_directory_path),
        ),
        migrations.AddField(
            model_name='project',
            name='background_2',
            field=models.ImageField(blank=True, null=True, upload_to=custom_admin.apps.back1_project_directory_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(default='#ABCDEF', max_length=7, validators=[django.core.validators.RegexValidator(message='Введите код цвета.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
    ]
