# Generated by Django 5.0.2 on 2024-03-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0005_project_background_1_project_background_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bigphotoproject',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='smallphotoproject',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
    ]
