# Generated by Django 5.0.2 on 2024-03-02 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0006_alter_bigphotoproject_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='about_content',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='service',
            name='content_sec1',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='service',
            name='content_sec2',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='service',
            name='title_sec1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='service',
            name='title_sec2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='about',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='ProcessDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('content', models.CharField(default='', max_length=2000)),
                ('index_number', models.IntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='custom_admin.service')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
