# Generated by Django 5.0.2 on 2024-03-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0007_project_about_content_service_content_sec1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processdevelopment',
            name='index_number',
            field=models.IntegerField(unique=True),
        ),
    ]
