# Generated by Django 5.0.2 on 2024-03-03 10:54

import custom_admin.apps
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0009_alter_processdevelopment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=custom_admin.apps.cover_project_directory_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='background_2',
            field=models.ImageField(blank=True, null=True, upload_to=custom_admin.apps.back2_project_directory_path),
        ),
    ]
