# Generated by Django 5.0.2 on 2024-03-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0010_project_cover_alter_project_background_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigphotoproject',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='smallphotoproject',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
