# Generated by Django 5.0.2 on 2024-03-05 15:21

import custom_admin.apps
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0012_project_description_alter_project_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processdevelopment',
            options={'ordering': ['index_number', 'id']},
        ),
        migrations.AddField(
            model_name='post',
            name='middle_sec_text',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='service',
            name='goals_objectives_text',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='service',
            name='photo_present_project',
            field=models.ImageField(blank=True, null=True, upload_to=custom_admin.apps.present_project_directory_path),
        ),
        migrations.AddField(
            model_name='service',
            name='title_present_project',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='service',
            name='title_process',
            field=models.CharField(default='', max_length=150),
        ),
    ]
