# Generated by Django 5.0.2 on 2024-03-05 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0014_service_mini_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processdevelopment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='custom_admin.service'),
        ),
    ]
