# Generated by Django 5.0.2 on 2024-03-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0015_alter_processdevelopment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='middle_sec_text',
            field=models.CharField(default='', max_length=500),
        ),
    ]
