# Generated by Django 5.0.2 on 2024-03-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0016_alter_post_content_alter_post_middle_sec_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.CharField(default='', max_length=300),
        ),
    ]
