# Generated by Django 5.0.2 on 2024-03-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0018_alter_task_options_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
