# Generated by Django 5.0.2 on 2024-03-10 15:05

import custom_admin.apps
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0019_alter_task_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('position', models.TextField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=custom_admin.apps.site_user_directory_path)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
