# Generated by Django 5.0.2 on 2024-03-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0020_siteuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='position',
            field=models.TextField(max_length=100),
        ),
    ]
