# Generated by Django 5.0.2 on 2024-03-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0021_alter_siteuser_first_name_alter_siteuser_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigphotoproject',
            name='index_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='smallphotoproject',
            name='index_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
