# Generated by Django 5.0.2 on 2024-03-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0022_bigphotoproject_index_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='index_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
