# Generated by Django 5.0.2 on 2024-03-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0023_project_index_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='index_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
