# Generated by Django 5.0.2 on 2024-03-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0025_alter_bigphotoproject_index_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigphotoproject',
            name='index_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processdevelopment',
            name='index_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='index_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smallphotoproject',
            name='index_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
