# Generated by Django 5.0.2 on 2024-03-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0026_alter_bigphotoproject_index_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='service',
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(related_name='projects', to='custom_admin.service'),
        ),
    ]
