# Generated by Django 5.0.2 on 2024-03-12 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0027_remove_project_service_project_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='services',
            new_name='service',
        ),
    ]
