# Generated by Django 5.0.2 on 2024-03-16 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0029_remove_project_service_projectblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectblock',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='custom_admin.project'),
        ),
    ]
