# Generated by Django 5.0.2 on 2024-03-16 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0030_alter_projectblock_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectblock',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.service'),
        ),
    ]
