# Generated by Django 5.0.2 on 2024-03-17 20:38

import custom_admin.apps
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0033_alter_projectblock_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectblock',
            name='photo',
        ),
        migrations.CreateModel(
            name='ProjectBlockPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('upload', models.ImageField(upload_to=custom_admin.apps.block_project_directory_path)),
                ('index_number', models.IntegerField(blank=True, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_photos', to='custom_admin.project')),
            ],
        ),
    ]
