# Generated by Django 5.0.2 on 2024-03-17 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0034_remove_projectblock_photo_projectblockphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectblockphoto',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_photos', to='custom_admin.projectblock'),
        ),
    ]
