# Generated by Django 5.0.2 on 2024-03-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0035_alter_projectblockphoto_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processdevelopment',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
