# Generated by Django 5.0.2 on 2024-03-17 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0036_alter_processdevelopment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processdevelopment',
            name='index_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processdevelopment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='custom_admin.service'),
        ),
    ]
