# Generated by Django 5.0.2 on 2024-04-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0037_alter_processdevelopment_index_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='mini_text',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_present_project',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
