# Generated by Django 5.0.2 on 2024-04-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0038_alter_service_mini_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigphotoproject',
            name='title',
            field=models.CharField(default='', max_length=65535),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_sec1',
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_sec2',
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=models.CharField(default='', max_length=65535),
        ),
        migrations.AlterField(
            model_name='post',
            name='middle_sec_text',
            field=models.CharField(default='', max_length=65535),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_sec1',
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_sec2',
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='processdevelopment',
            name='content',
            field=models.CharField(default='', max_length=65535),
        ),
        migrations.AlterField(
            model_name='processdevelopment',
            name='title',
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='project',
            name='about',
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='project',
            name='about_content',
            field=models.CharField(default='', max_length=65535),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution',
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='projectblock',
            name='description',
            field=models.CharField(blank=True, max_length=65535),
        ),
        migrations.AlterField(
            model_name='projectblock',
            name='title',
            field=models.CharField(blank=True, max_length=65535),
        ),
        migrations.AlterField(
            model_name='projectblockphoto',
            name='title',
            field=models.CharField(blank=True, default='', max_length=65535),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(default='', max_length=65535),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='service',
            name='content_sec1',
            field=models.CharField(default='', max_length=65535),
        ),
        migrations.AlterField(
            model_name='service',
            name='content_sec2',
            field=models.CharField(default='', max_length=65535),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(default='', max_length=65535),
        ),
        migrations.AlterField(
            model_name='service',
            name='goals_objectives_text',
            field=models.CharField(default='', max_length=65535),
        ),
        migrations.AlterField(
            model_name='service',
            name='mini_text',
            field=models.CharField(blank=True, default='', max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=65535, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_present_project',
            field=models.CharField(blank=True, default='', max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_process',
            field=models.CharField(default='', max_length=65535),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_sec1',
            field=models.CharField(default='', max_length=65535),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_sec2',
            field=models.CharField(default='', max_length=65535),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='first_name',
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='last_name',
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='position',
            field=models.TextField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='smallphotoproject',
            name='title',
            field=models.CharField(default='', max_length=65535),
        ),
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=65535),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='task',
            name='phone_number',
            field=models.CharField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.TextField(blank=True, max_length=65535),
        ),
    ]
